# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitAge < Formula
  desc "git-age is a smudge/clean filter to encrypt/decrypt files in a git repository transparently"
  homepage "https://github.com/prskr/git-age"
  version "0.2.4"
  license "MIT"

  depends_on "git" if OS.mac?

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/prskr/git-age/releases/download/v0.2.4/git-age_Darwin_x86_64.tar.gz"
      sha256 "126280a255c2a8a211774862e951ce481b1ccd468d94b96971ea355ba47ae05b"

      def install
        bin.install "git-age"
        man1.install "docs/git-age.1.gz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/prskr/git-age/releases/download/v0.2.4/git-age_Darwin_arm64.tar.gz"
      sha256 "a304edfdff559aa5c3aa0d0e3baacd26bce5fd2b56c856f0e135e883a3e60a91"

      def install
        bin.install "git-age"
        man1.install "docs/git-age.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/prskr/git-age/releases/download/v0.2.4/git-age_Linux_x86_64.tar.gz"
        sha256 "20c061d768e11ca7063d3d34fb3bf80c0a7997d7583ee41f3ecdf105c47de003"

        def install
          bin.install "git-age"
          man1.install "docs/git-age.1.gz"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/prskr/git-age/releases/download/v0.2.4/git-age_Linux_arm64.tar.gz"
        sha256 "fcc38ea8dccca7c417c499e87f8bb4a64f8c115b0a16852342a16a5be091a945"

        def install
          bin.install "git-age"
          man1.install "docs/git-age.1.gz"
        end
      end
    end
  end

  test do
    system "#{bin}/git-age --help"
  end
end
