# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitAgeKeyringAgent < Formula
  desc "git-age agent to store and load identities from your OS' keyring
"
  homepage "https://github.com/prskr/git-age-keyring-agent"
  version "0.1.4"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/prskr/git-age-keyring-agent/releases/download/v0.1.4/git-age-keyring-agent_Darwin_x86_64.tar.gz"
      sha256 "e86fd6fcab2fdee252f52d627d5c0c23c95b87bcbc71c17d66ffeebe041cee6b"

      def install
        bin.install "git-age-keyring-agent"
      end
    end
    on_arm do
      url "https://github.com/prskr/git-age-keyring-agent/releases/download/v0.1.4/git-age-keyring-agent_Darwin_arm64.tar.gz"
      sha256 "65b1cfae1bee468ec78ede0c916b799294fda802279e6737e4aa11a02f495fd4"

      def install
        bin.install "git-age-keyring-agent"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/prskr/git-age-keyring-agent/releases/download/v0.1.4/git-age-keyring-agent_Linux_x86_64.tar.gz"
        sha256 "dbf1facf2e1877472163c759509f0a760380b654c2f4908095dbd2fcf5023317"

        def install
          bin.install "git-age-keyring-agent"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/prskr/git-age-keyring-agent/releases/download/v0.1.4/git-age-keyring-agent_Linux_arm64.tar.gz"
        sha256 "7f33a4685b0dcbe97387a3e6769df27f2f044cfdb3f32cb86ea60501228f27ba"

        def install
          bin.install "git-age-keyring-agent"
        end
      end
    end
  end

  service do
    run [opt_bin/"git-age-keyring-agent", "serve"]
    keep_alive true
  end

  test do
    system "#{bin}/git-age-keyring-agent --help"
  end
end
