# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitAgeKeyringAgent < Formula
  desc "git-age agent to store and load identities from your OS' keyring
"
  homepage "https://github.com/prskr/git-age-keyring-agent"
  version "0.1.2"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/prskr/git-age-keyring-agent/releases/download/v0.1.2/git-age-keyring-agent_Darwin_x86_64.tar.gz"
      sha256 "9457fa02ca03e74ee903ff3bfbb92a4f9e1ac614dc4f678b2414f7bb258e63e1"

      def install
        bin.install "git-age-keyring-agent"
      end
    end
    on_arm do
      url "https://github.com/prskr/git-age-keyring-agent/releases/download/v0.1.2/git-age-keyring-agent_Darwin_arm64.tar.gz"
      sha256 "9f01e3b623ab26b08ae73d42a12aefba28f31af453bf1a4a720535f186db622e"

      def install
        bin.install "git-age-keyring-agent"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/prskr/git-age-keyring-agent/releases/download/v0.1.2/git-age-keyring-agent_Linux_x86_64.tar.gz"
        sha256 "70f74f00eceab85e38b77a83c1cb7bc79cb47ea86118bd05e24c20cd303040ca"

        def install
          bin.install "git-age-keyring-agent"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/prskr/git-age-keyring-agent/releases/download/v0.1.2/git-age-keyring-agent_Linux_arm64.tar.gz"
        sha256 "3b24e7814a06605cc07e0921bcf06a2ed96a7d8863d7f3d5d7b618e4f91fbba6"

        def install
          bin.install "git-age-keyring-agent"
        end
      end
    end
  end

  service do
    run [opt_bin/"git-age-keyring-agent"]
    keep_alive true
  end

  test do
    system "#{bin}/git-age-keyring-agent --help"
  end
end
